In [1]:
import numpy as np

In [ ]:
mat2 = np.array([1, 10, 20, 30]).reshape(2, 2)

In [17]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,np.nan]])

In [21]:
b = np.array( [[1,2,3],
               [4,5,6]])

In [22]:
b.shape

(2, 3)

In [23]:
(b%2==0).any(axis=0)

array([ True,  True,  True])

In [26]:
(a%2==0).all(axis=0)

array([False,  True, False, False])

In [24]:
(b%2==0).any(axis=1)

array([ True,  True])

In [20]:
(a%2==0).any(axis=0)

array([False,  True, False,  True])

In [10]:
(a%2==0).any(axis=1)

array([ True,  True,  True])

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [18]:
a[(np.isnan(a)).any(axis=1)]

array([[ 9., 10., 11., nan]])

In [19]:
a[0]

array([1., 2., 3., 4.])

In [12]:
a[(a%2==0).any(axis=0)]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 4

In [7]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12])

In [5]:
a>5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [6]:
a[[[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]]]

array([ 6,  7,  8,  9, 10, 11, 12])

In [15]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])

In [5]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
mask1 = (a%2==0).any(axis=1)

In [12]:
mask2 = (a%2==0).any(axis=0)

In [16]:
mask3 = (b%2==0).any(axis=1)

In [17]:
mask4 = (b%2==0).any(axis=0)

In [13]:
a[mask1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[mask2]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 4

In [18]:
b[mask3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [19]:
b[mask4]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16]])